title = "Arjun Dhungel"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Arjun Dhungel"
  headline = "Hello! I'm an IT student deeply immersed in the world of social networks, particularly YouTube, and networking. Beyond my technical expertise, I'm fueled by a passion for singing and vlogging."
  image = "arjun.jpeg"
  links = [
    { link = { href = "/arjunCv.pdf", text = "Download my CV >>", icon = "" } },
    { email = "mailto:aaarjun6654@gmail.com"},
    { youtube = "https://www.youtube.com/@ararjunofficial4523" },
    { link = { href = "styles/", text = "Reach me", target = "_self" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
