name = "Arjun Dhungel"
license = "MIT"
description = "A personal portfolio website"

tags = ["minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["dark mode", "emoji"]

[author]
  name = "Suhesh Kasti"
  homepage = "https://suhesh.com.np/"
